# Generated by Django 4.2.16 on 2024-11-03 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('rut_usuario', models.CharField(max_length=20, unique=True, verbose_name='rut_usuario')),
                ('profile_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='NuevoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_nombre', models.CharField(max_length=60)),
                ('p_img', models.ImageField(null=True, upload_to='')),
                ('p_descripcion', models.TextField(null=True)),
                ('p_habilitar', models.IntegerField(choices=[(0, 'deshabilitado'), (1, 'habilitado')], default=1)),
                ('p_account_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('p_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTags', models.CharField(max_length=90)),
                ('categoriaTags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTrans', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TagsPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPublicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.nuevoproducto')),
                ('tagPublicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tags')),
            ],
        ),
        migrations.AddField(
            model_name='nuevoproducto',
            name='p_tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tags'),
        ),
        migrations.AddField(
            model_name='nuevoproducto',
            name='p_tipoTrans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipotrans'),
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensajePost', models.TextField()),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuarioPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioPosteo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchValoracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valormatch', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('opinion', models.TextField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('dueño_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_dueño', to=settings.AUTH_USER_MODEL)),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_evaluador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valoración de Match',
                'verbose_name_plural': 'Valoraciones de Matches',
            },
        ),
        migrations.CreateModel(
            name='MatchProductoRegalo',
            fields=[
                ('PostMatch', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_propuesta', models.DateTimeField(auto_now_add=True)),
                ('estado_solicitud', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
                ('confirmacion_match', models.IntegerField(choices=[(0, 'No confirmado'), (1, 'Confirmado')], default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_producto', to='core.nuevoproducto')),
                ('usuario_dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_dueno', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_solicitante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchProductoCambio',
            fields=[
                ('PostMatch', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_propuesta', models.DateTimeField(auto_now_add=True)),
                ('estado_solicitud', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
                ('confirmacion_match', models.IntegerField(choices=[(0, 'No confirmado'), (1, 'Confirmado')], default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_cambio_producto', to='core.nuevoproducto')),
                ('producto_propuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_cambio_propuesto', to='core.nuevoproducto')),
                ('usuario_dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_cambio_dueno', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_cambio_solicitante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='matchvaloracion',
            constraint=models.UniqueConstraint(fields=('dueño_producto', 'evaluador', 'content_type', 'object_id'), name='unique_valoracion_match'),
        ),
    ]
