# Generated by Django 4.2.16 on 2024-11-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_nuevoproducto_p_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipotrans',
            name='nombreTrans',
            field=models.CharField(max_length=30),
        ),
    ]
