# Generated by Django 4.2.16 on 2024-11-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tipotrans_nombretrans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchvaloracion',
            name='valormatch',
            field=models.IntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')]),
        ),
    ]
